# Site settings
title: Notes from Journey 
header-img: img/home-bg.png
email: haydengolds@gmail.com
copyright_name: WindierGnu
description: > # this means to ignore newlines until "baseurl:"
  My point of view
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: windiergnu
github_username:  WindierGnu
learn_profile: WindierGnu
email_username: haydengolds@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
